-- 1)what is the total reveunue generated by the male & Female customers?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

--2) which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3) which are the top 5 products with highest average review Rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2) as " Average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
--4) comapre the average purchase amounts between standard and express shipping.
select shipping_type,Round(AVG(purchase_amount),2) as "Average amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5) do subscribed customers spend more? compare average spent and total revenue between subscribers and non suscribers?
select subscription_status,SUM(purchase_amount) as Total_revenue ,ROUND(Avg(purchase_amount),2) as Average_spent ,
COUNT(customer_id) as total_Customer
from customer
group by subscription_status
order by Total_revenue,Average_spent desc;

--6) Which 5 Product have the highest Percentage of purchase with discounts applied?
select item_purchased,
Round(100 * Sum(case WHEN discount_applied = 'Yes' Then 1 else 0 end)/Count(*),2) as discount_rate
from customer
group by item_purchased 
order by discount_rate Desc
limit 5;

--7)Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
 	case 
	 when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
	 from customer
)
select customer_segment,count(*) as Number_Of_customers
from customer_type 
group by customer_segment;


--8)what are the top 3 purchased products within each category
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() over(
	PARTITION by category 
	order by count(customer_id) DESC	
) as item_rank
from customer
group by category , item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--9)Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as Total_revenue
from customer 
group by age_group
order by Total_revenue DESC