-- 1)what is the total reveunue generated by the male & Female customers?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

--2) which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3) which are the top 5 products with highest average review Rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2) as " Average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
--4) comapre the average purchase amounts between standard and express shipping.
select shipping_type,Round(AVG(purchase_amount),2) as "Average amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5) do subscribed customers spend more? compare average spent and total revenue between subscribers and non suscribers?
select subscription_status,SUM(purchase_amount) as Total_revenue ,ROUND(Avg(purchase_amount),2) as Average_spent ,
COUNT(customer_id) as total_Customer
from customer
group by subscription_status
order by Total_revenue,Average_spent desc;

--6) Which 5 Product have the highest Percentage of purchase with discounts applied?
select item_purchased,
ROUND((purchase_amount/(select Sum(purchase_amount) from customer)) * 100,2) as Percentage, discount_applied
from customer 
where discount_applied = 'Yes'
order by Percentage DESC
limit 5;
